export type Face = {
  "object": string,
  "name": string,
  "mana_cost": string,
  "type_line": string,
  "oracle_text": string,
  "colors": string[],
  "power": string,
  "toughness": string,
  "artist": string,
  "artist_id": string,
  "illustration_id": string,
  "image_uris": {
    "small": string,
    "normal": string,
    "large": string,
    "png": string,
    "art_crop": string,
    "border_crop": string
  }
}

export type scryCard = {
  "object": string,
  "id": string,
  "oracle_id": string,
  "multiverse_ids": number[],
  "tcgplayer_id": number,
  "cardmarket_id": number,
  "name": string,
  "lang": string,
  "released_at": string,
  "uri": string,
  "scryfall_uri": string,
  "layout": string,
  "highres_image": true,
  "image_status": string,
  "image_uris": {
    "small": string,
    "normal": string,
    "large": string,
    "png": string,
    "art_crop": string,
    "border_crop": string
  },
  "mana_cost": string, // maybe make an object later?
  "cmc": number,
  "type_line": string,
  "oracle_text": string, //object?
  "power": string,
  "toughness": string,
  "colors": string[],
  "color_identity": string[],
  "keywords": string[],
  "card_faces": Face[],
  "all_parts": [
    {
      "object": string,
      "id": string,
      "component": string,
      "name": string,
      "type_line": string,
      "uri": string
    },
    {
      "object": string,
      "id": string,
      "component": string,
      "name": string,
      "type_line": string,
      "uri": string
    }
  ],
  "legalities": {
    "standard": string,
    "future": string,
    "historic": string,
    "timeless": string,
    "gladiator": string,
    "pioneer": string,
    "explorer": string,
    "modern": string,
    "legacy": string,
    "pauper": string,
    "vintage": string,
    "penny": string,
    "commander": string,
    "oathbreaker": string,
    "standardbrawl": string,
    "brawl": string,
    "alchemy": string,
    "paupercommander": string,
    "duel": string,
    "oldschool": string,
    "premodern": string,
    "predh": string
  },
  "games": string[],
  "reserved": boolean,
  "game_changer": boolean,
  "foil": boolean,
  "nonfoil": boolean,
  "finishes": string[]
  "oversized": boolean,
  "promo": boolean,
  "reprint": boolean,
  "variation": boolean,
  "set_id": string,
  "set": string,
  "set_name": string,
  "set_type": string,
  "set_uri": string,
  "set_search_uri": string,
  "scryfall_set_uri": string,
  "rulings_uri": string,
  "prints_search_uri": string,
  "collector_number": string,
  "digital": false,
  "rarity": string,
  "card_back_id": string,
  "artist": string,
  "artist_ids": string[],
  "illustration_id": string,
  "border_color": string,
  "frame": string,
  "frame_effects": string[],
  "security_stamp": string,
  "full_art": false,
  "textless": false,
  "booster": false,
  "story_spotlight": false,
  "edhrec_rank": number,
  "prices": {
    usd: string | null,
    "usd_foil": string | null,
    "usd_etched": string | null,
    "eur": string | null,
    "eur_foil": string | null,
    "tix": null
  },
  "related_uris": {
    "gatherer": string,
    "tcgplayer_infinite_articles": string,
    "tcgplayer_infinite_decks": string,
    "edhrec": string
  },
  "purchase_uris": {
    "tcgplayer": string,
    "cardmarket": string,
    "cardhoarder": string
  }
}