export const colorNames = {
    "": "Colorless",
    "white": "Mono White",
    "blue": "Mono Blue",
    "black": "Mono Black",
    "red": "Mono Red",
    "green": "Mono Green",
    "whiteblue": "Azorius",
    "whiteblack": "Orzhov",
    "whitered": "Boros",
    "whitegreen": "Selesnya",
    "blueblack": "Dimir",
    "bluered": "Izzet",
    "bluegreen": "Simic",
    "blackred": "Rakdos",
    "blackgreen": "Golgari",
    "redgreen": "Gruul",
    "whiteblueblack": "Esper",
    "whitebluered": "Jeskai",
    "whitebluegreen": "Bant",
    "whiteblackred": "Mardu",
    "whiteblackgreen": "Abzan",
    "whiteredgreen": "Naya",
    "blueblackred": "Grixis",
    "blueblackgreen": "Sultai",
    "blueredgreen": "Temur",
    "blackredgreen": "Jund",
    "whiteblueblackred": "Sans Green",
    "whiteblueblackgreen": "Sans Red",
    "whiteblueredgreen": "Sans Black",
    "whiteblackredgreen": "Sans Blue",
    "blueblackredgreen": "Sans White",
    "whiteblueblackredgreen": "WUBRG"
}